language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.1
otp_release:
  - 21.2
  - 20.3
  - 19.3
matrix:
  exclude:
    - otp_release: 21.2
      elixir: 1.3.4
    - otp_release: 21.2
      elixir: 1.4.5
    - otp_release: 21.2
      elixir: 1.5.3
    - otp_release: 20.3
      elixir: 1.3.4
    - otp_release: 19.3
      elixir: 1.8.1
  include:
    - otp_release: 18.3
      elixir: 1.5.3
  allow_failures:
    - otp_release: 18.3
script:
  - scripts/run_tests
