branches:
  only:
  - master
  - develop
language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.2
otp_release:
  - 21.3
  - 20.3.8
  - 19.3
matrix:
  exclude:
    - otp_release: 21.3
      elixir: 1.3.4
    - otp_release: 21.3
      elixir: 1.4.5
    - otp_release: 21.3
      elixir: 1.5.3
    - otp_release: 20.3.8
      elixir: 1.3.4
    - otp_release: 19.3
      elixir: 1.8.2
  include:
    - otp_release: 18.3
      elixir: 1.5.3
  allow_failures:
    - otp_release: 18.3
script:
  - scripts/test
