language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.0-rc.1
otp_release:
  - 21.1
  - 20.2
  - 19.3
matrix:
  exclude:
    - otp_release: 21.1
      elixir: 1.3.4
    - otp_release: 21.1
      elixir: 1.4.5
    - otp_release: 21.1
      elixir: 1.5.3
    - otp_release: 20.2
      elixir: 1.3.4
    - otp_release: 19.3
      elixir: 1.8.0-rc.1
  include:
    - otp_release: 18.3
      elixir: 1.5.3
  allow_failures:
    - otp_release: 18.3
script:
  - MIX_ENV=test scripts/run_formatter
  - MIX_ENV=test scripts/check_warnings
  - MIX_ENV=test mix test
  - MIX_ENV=test_phoenix mix test
  - rm -r priv/*appsignal* && MIX_ENV=test_no_nif mix test
